### ISSUE TITLE
Unable to obtain OAuth 2.0 token

### ISSUE THREAD

**Issue by theminji** [armintum/MusicLM#1]
![image](https://github.com/armintum/MusicLM/assets/123284838/c9a65d17-3c30-4459-aa47-0bd222dfb2e5)
I am unable to obtain the OAuth 2.0 token when I run the code. I set the .env file with my credentials, and it is logging in, however it is not getting the token?

**Comment by plon** [comment]
Do you have access to the AI Test Kitchen?

**Comment by theminji** [comment]
> ch

yes i do, and i use it all the time

**Comment by theminji** [comment]
oh ok i need access to the test kitchen app, not just musiclm. got it. I just signed in on my other account and it works now! Thanks
